; Discord Automation Script
; Generated by ClankerTV Bot
; Press Ctrl+D to run, F1 to get coordinates, Esc to exit

; Define your click coordinates here (replace with actual coordinates)
Click1X := 400
Click1Y := 300
Click2X := 600
Click2Y := 500

^d::
    ; Activate Discord window
    WinActivate, ahk_exe Discord.exe
    WinWaitActive, ahk_exe Discord.exe, , 3
    
    ; Make Discord fullscreen
    Send, {F11}
    Sleep, 1000
    
    ; First click
    Click, %Click1X%, %Click1Y%
    Sleep, 500
    
    ; Second click
    Click, %Click2X%, %Click2Y%
    
    ; Optional: Exit fullscreen after 2 seconds
    Sleep, 2000
    Send, {F11}
return

; Press F1 to get current mouse coordinates
F1::
MouseGetPos, xpos, ypos
MsgBox, Discord Coordinates: X=%xpos% Y=%ypos%
return

; Press Esc to stop script
Esc::ExitApp